#server:
#  port: 8080
#girl:
#  cupSize: B
#  age: 23
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?useSSL=true
    username: root
    data-password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true